### ISSUE TITLE
Bash waybackurl command not found

### ISSUE THREAD

**Issue by thevillagehacker** [tomnomnom/waybackurls#20]
I tried installing tool using `go get github.com/tomnomnom/waybackurls` and it seems installed no errors popped and when i tried to use the tool using the command `cat domains.txt | waybackurls > urls` it poped like 
```bash
naveenj@Saturn:|08:25 AM|~$ cat domains.txt | waybackurls > urls
-bash: waybackurls: command not found
```

**Comment by 666reda** [comment]
Try to add `export PATH="$PATH:$HOME/go/bin` to your `~/bashrc` file

**Comment by thevillagehacker** [comment]
Thanks working fine now...

**Comment by siriusblack01** [comment]
> export PATH="$PATH:$HOME/go/bin

It didn't work for me.
I use oh-my-zsh, and I added it to `~/.zshrc` too, but it didn't help.

**Comment by koushikfs** [comment]
run export PATH="$PATH:[path to /go/bin]" on terminal, $HOME is just a path to user folder. so remove $HOME and give exact path, because your go folder might be in different location ig.
