### ISSUE TITLE
Fix CommonCrawl URLs

### ISSUE THREAD

**Issue by Rhynorater** [tomnomnom/waybackurls#4]
The current CommonCrawl fetch url is this:
```
http://index.commoncrawl.org/CC-MAIN-2018-22-index?url=*.%s&output=json
```
I would suggest that it should be this:
```
http://index.commoncrawl.org/CC-MAIN-2018-22-index?url=*.%s/*&output=json
```
See the difference in results in the following:
http://index.commoncrawl.org/CC-MAIN-2018-22-index?url=blog.innerht.ml/*&output=json
as opposed to how you currently have it:
http://index.commoncrawl.org/CC-MAIN-2018-22-index?url=blog.innerht.ml&output=json

Thanks,
Justin

**Comment by tomnomnom** [comment]
Ah! Good spot! Should be sorted now :)
