### ISSUE TITLE
waybackurls not working

### ISSUE THREAD

**Issue by sushantsingh7** [tomnomnom/waybackurls#47]
![image](https://user-images.githubusercontent.com/132044258/235357434-acfd77f3-f864-4030-baff-7b561001b0b1.png)

i am trying to work with waybackurls but not able to execute command
saying command not found tried everything from the net but not working someone can help me with that

**Comment by ROF618** [comment]
It could be that the go/bin directory is not in your $PATH. Have you been able to run other go applications on that system?

**Comment by sushantsingh7** [comment]
> It could be that the go/bin directory is not in your $PATH. Have you been able to run other go applications on that system?
Hey @ROF618 hey man thanks for the advice actually i was able to run the command after running the mod.go and sending the file to /bin directory

**Comment by ROF618** [comment]
> > It could be that the go/bin directory is not in your $PATH. Have you been able to run other go applications on that system?
> > Hey @ROF618 hey man thanks for the advice actually i was able to run the command after running the mod.go and sending the file to /bin directory

Glad to hear it man. Happy hunting!
