### ISSUE TITLE
Json Output

### ISSUE THREAD

**Issue by jaikishantulswani** [tomnomnom/waybackurls#5]
Hey @tomnomnom ,
Is there any switch to get output in json format.

**Comment by tomnomnom** [comment]
Hi @jaikishantulswani, thanks for raising an issue!

There isn't a switch for that I'm afraid. You did prompt me to write a small tool over my lunch break that might help though: https://github.com/tomnomnom/hacks/tree/master/tojson

With that tool installed you can run a command like `waybackurls example.com | tojson` and get the output in JSON format :)

**Comment by jaikishantulswani** [comment]
Thank You @tomnomnom :100:

**Comment by tomnomnom** [comment]
No problemo :)
